<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SC701.Data\SC701.Data.csproj" />
    <ProjectReference Include="..\SC701.Models\SC701.Models.csproj" />
  </ItemGroup>

</Project>
